apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: finalwiki
  name: finalwiki
spec:
  ports:
  - nodePort:31845
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: finalwiki
  type: NodePort
status:
  loadBalancer: {}
