apiVersion: v1
kind: Service
metadata:
  name: nmariadb
  labels:
    app: nmariadb
spec:
  ports:
    - port: 3306
      name: nmysql
  selector:
    app: nmariadb
    tier: nmysql-cache
  #clusterIP: None
